### ISSUE TITLE
[Linux] File name case issue Map1OutLine.svg

### ISSUE THREAD

**Issue by rchastain** [Lulu04/LittleRedRidingHood#3]
Hello.

The file name is **Map1Outline.svg** but the program expects **Map1OutLine**.

![unable-load-svg](https://github.com/user-attachments/assets/670953bc-e7a0-4f30-9d6f-6a4e8226e2ff)

**Comment by rchastain** [comment]
After I fixed the file name and relaunched the application, I get an access violation, and the screen stays black. Maybe other file name issues?

**Comment by Lulu04** [comment]
Hi rchastain, thank you to test the game.

I've just tested the game on my ubuntu 20.04 (virtual machine) and I can not reproduce the issue.
May be you download the game when he was not yet sufficiently advanced ?

It is preferable to download a release, but I haven't made any yet. This will be done shortly.

For now, you can try to download the repository again, I've made some changes since yesterday. I think the issue is gone.

in the Pin Forest, use the UP and DOWN keys to move, ACTION1 for the bow, ACTION2 for the second weapon.
In the Montain Peaks, use the LEFT and RIGHT to move, ACTION1 to decrease the speed.

Regards

**Comment by Lulu04** [comment]
EDIT: You right, the filename have a charcase error.
this is corrected in this  #PR #15.

This shows that running Linux in a virtual machine running on Windows doesn't generate case errors on file names!
I'll try to be more vigilant in the future

Thank you very much Roland !

**Comment by rchastain** [comment]
I confirm that all seem to work perfectly now. Nice game!

**Comment by Lulu04** [comment]
I'm glad, thank you!
